name: weather_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  dio: ^5.9.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.10.0
  geolocator: ^14.0.2
  intl: ^0.20.2
  get_it: ^9.2.0
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  rxdart: ^0.28.0
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.11.1
  freezed: ^3.2.5
  json_serializable: ^6.12.0

flutter:
  uses-material-design: true
